CREATE TABLE vehicles
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active            VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    version           BIGINT        NOT NULL DEFAULT 0,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP,
    make              VARCHAR(100)  NOT NULL,
    model             VARCHAR(100)  NOT NULL,
    year              INTEGER       NOT NULL,
    license_plate     VARCHAR(20)   NOT NULL,
    status            VARCHAR(30)   NOT NULL DEFAULT 'AVAILABLE',
    last_latitude     DOUBLE PRECISION,
    last_longitude    DOUBLE PRECISION,
    last_location_at  TIMESTAMP,
    CONSTRAINT pk_vehicles PRIMARY KEY (id)
);

ALTER TABLE vehicles ADD CONSTRAINT uc_vehicles_license_plate UNIQUE (license_plate);