CREATE TABLE drivers
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMP,
    updated_at      TIMESTAMP,
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    phone           VARCHAR(30),
    license_number  VARCHAR(50)  NOT NULL,
    vehicle_id      BIGINT,
    CONSTRAINT pk_drivers PRIMARY KEY (id)
);

ALTER TABLE drivers ADD CONSTRAINT uc_drivers_license_number UNIQUE (license_number);
ALTER TABLE drivers ADD CONSTRAINT fk_drivers_on_vehicles FOREIGN KEY (vehicle_id) REFERENCES vehicles (id);