CREATE TABLE maintenance
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active       VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    version      BIGINT        NOT NULL DEFAULT 0,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    vehicle_id   BIGINT        NOT NULL,
    description  VARCHAR(500),
    service_date DATE          NOT NULL,
    cost         NUMERIC(10,2),
    CONSTRAINT pk_maintenance PRIMARY KEY (id)
);

ALTER TABLE maintenance ADD CONSTRAINT fk_maintenance_on_vehicles FOREIGN KEY (vehicle_id) REFERENCES vehicles (id);

CREATE INDEX idx_maintenance_vehicles_id ON maintenance (vehicle_id);