CREATE TABLE locations
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    active       VARCHAR(20)       NOT NULL DEFAULT 'ACTIVE',
    version      BIGINT            NOT NULL DEFAULT 0,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    vehicle_id   BIGINT            NOT NULL,
    latitude     DOUBLE PRECISION  NOT NULL,
    longitude    DOUBLE PRECISION  NOT NULL,
    recorded_at  TIMESTAMP,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

ALTER TABLE locations ADD CONSTRAINT fk_locations_on_vehicles FOREIGN KEY (vehicle_id) REFERENCES vehicles (id);

CREATE INDEX idx_locations_vehicles_id_recorded_at ON locations (vehicle_id, recorded_at DESC);